HOCKING-clusterpath-poster.pdf: HOCKING-clusterpath-poster.tex geometry.tex inria-logo.pdf posterDIGITEO.cls moons.png
	pdflatex HOCKING-clusterpath-poster
geometry.tex: figures.R
	R --vanilla < figures.R
