
2011-07-01-HOCKING-icml-clusterpath-slides.pdf: 2011-07-01-HOCKING-icml-clusterpath-slides.Rnw
	R CMD pgfsweave 2011-07-01-HOCKING-icml-clusterpath-slides.Rnw
2011-07-01-HOCKING-icml-clusterpath-slides.Rnw: 2011-07-01-HOCKING-icml-clusterpath-slides-in.Rnw make_figures.py panels.Rnw
	python make_figures.py